In [ ]:
!pip install -U scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.4/13.4 MB 88.9 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.3.2
    Uninstalling scikit-learn-1.3.2:
      Successfully uninstalled scikit-learn-1.3.2


In [ ]:
!pip install qiskit

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 58.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 13.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 80.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.4/39.4 MB 13.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.5/107.5 kB 10.8 MB/s eta 0:00:00


In [ ]:
!pip install qiskit_algorithms

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 308.6/308.6 kB 6.4 MB/s eta 0:00:00


In [ ]:
!pip install qiskit_machine_learning

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 4.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.8/97.8 kB 8.4 MB/s eta 0:00:00
  Created wheel for fastdtw: filename=fastdtw-0.3.4-cp310-cp310-linux_x86_64.whl size=512610 sha256=dd36c1fdf717548380e07874bdd027af0914990c08b212e3e435d864c58439b6
  Stored in directory: /root/.cache/pip/wheels/73/c8/f7/c25448dab74c3acf4848bc25d513c736bb93910277e1528ef4
Successfully built fastdtw


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df_iris = pd.read_csv('/content/iris.csv')

In [ ]:
print(df_iris)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

In [ ]:
iris_data = pd.DataFrame(df_iris, columns=['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'])
iris_target = pd.DataFrame(df_iris, columns=['Species'])

In [ ]:
x = iris_data[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = iris_target[["Species"]]
x_train,x_test, y_train, y_test=train_test_split(x,y,test_size=0.30)
C = 1.0
csvm_model = SVC()
csvm_model.fit(x_train.values, y_train.values.ravel())
csvm_pred = csvm_model.predict(x_test.values)
print("Confusion Matrix")
print(confusion_matrix(y_test, csvm_pred))
print("Classification Report")
print(classification_report(y_test, csvm_pred))
print("Predict the flower type for data Sepal (4.4, 4.4) and Petal (4.4, 4.4)")
csvm_model.predict([[4.4,4.4,4.4,4.4]])

Confusion Matrix
[[14  0  0]
 [ 0 14  3]
 [ 0  0 14]]
Classification Report
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       1.00      0.82      0.90        17
 Iris-virginica       0.82      1.00      0.90        14

       accuracy                           0.93        45
      macro avg       0.94      0.94      0.94        45
   weighted avg       0.95      0.93      0.93        45

Predict the flower type for data Sepal (4.4, 4.4) and Petal (4.4, 4.4)


array(['Iris-virginica'], dtype=object)

In [ ]:
from qiskit.circuit.library import ZZFeatureMap
from qiskit.primitives import Sampler
from qiskit_algorithms.state_fidelities import ComputeUncompute
from qiskit_machine_learning.kernels import FidelityQuantumKernel
adhoc_dimension=4
adhoc_feature_map = ZZFeatureMap(feature_dimension=adhoc_dimension, reps=2, entanglement="linear")
#classical data is encoded into qubit angles
sampler = Sampler()
fidelity = ComputeUncompute(sampler=sampler)
adhoc_kernel = FidelityQuantumKernel(fidelity=fidelity, feature_map=adhoc_feature_map)

In [ ]:
adhoc_feature_map.decompose().draw()

┌───┐┌─────────────┐                                          ┌───┐»
q_0: ┤ H ├┤ P(2.0*x[0]) ├──■────────────────────────────────────■──┤ H ├»
     ├───┤├─────────────┤┌─┴─┐┌──────────────────────────────┐┌─┴─┐└───┘»
q_1: ┤ H ├┤ P(2.0*x[1]) ├┤ X ├┤ P(2.0*(π - x[0])*(π - x[1])) ├┤ X ├──■──»
     ├───┤├─────────────┤└───┘└──────────────────────────────┘└───┘┌─┴─┐»
q_2: ┤ H ├┤ P(2.0*x[2]) ├──────────────────────────────────────────┤ X ├»
     ├───┤├─────────────┤                                          └───┘»
q_3: ┤ H ├┤ P(2.0*x[3]) ├───────────────────────────────────────────────»
     └───┘└─────────────┘                                               »
«             ┌─────────────┐                   »
«q_0: ────────┤ P(2.0*x[0]) ├───────────────────»
«             └─────────────┘              ┌───┐»
«q_1: ──────────────────────────────────■──┤ H ├»
«     ┌──────────────────────────────┐┌─┴─┐└───┘»
«q_2: ┤ P(2.0*(π - x[1])*(π - x[2])) ├┤ X ├──■──»
«     └──────────────────────────────┘└───┘┌─┴─┐»
«q_3: ─────────────────────────────────────┤ X ├»
«                                          └───┘»
«                                                                          »
«q_0: ──────────────────────────────────■──────────────────────────────────»
«             ┌─────────────┐         ┌─┴─┐┌──────────────────────────────┐»
«q_1: ────────┤ P(2.0*x[1]) ├─────────┤ X ├┤ P(2.0*(π - x[0])*(π - x[1])) ├»
«             └─────────────┘         └───┘└────────────┬───┬─────────────┘»
«q_2: ──────────────────────────────────■───────────────┤ H ├──────────────»
«     ┌──────────────────────────────┐┌─┴─┐             ├───┤              »
«q_3: ┤ P(2.0*(π - x[2])*(π - x[3])) ├┤ X ├─────────────┤ H ├──────────────»
«     └──────────────────────────────┘└───┘             └───┘              »
«                                                                   »
«q_0: ───────■──────────────────────────────────────────────────────»
«          ┌─┴─┐                                                    »
«q_1: ─────┤ X ├───────■────────────────────────────────────■───────»
«     ┌────┴───┴────┐┌─┴─┐┌──────────────────────────────┐┌─┴─┐     »
«q_2: ┤ P(2.0*x[2]) ├┤ X ├┤ P(2.0*(π - x[1])*(π - x[2])) ├┤ X ├──■──»
«     ├─────────────┤└───┘└──────────────────────────────┘└───┘┌─┴─┐»
«q_3: ┤ P(2.0*x[3]) ├──────────────────────────────────────────┤ X ├»
«     └─────────────┘                                          └───┘»
«                                          
«q_0: ─────────────────────────────────────
«                                          
«q_1: ─────────────────────────────────────
«                                          
«q_2: ──────────────────────────────────■──
«     ┌──────────────────────────────┐┌─┴─┐
«q_3: ┤ P(2.0*(π - x[2])*(π - x[3])) ├┤ X ├
«     └──────────────────────────────┘└───┘

In [ ]:
from qiskit_machine_learning.algorithms import QSVC

qsvm_model = QSVC(quantum_kernel=adhoc_kernel)

qsvm_model.fit(x_train, y_train.values.ravel())

qsvm_pred = qsvm_model.predict(x_test)
print("Confusion Matrix")
print(confusion_matrix(y_test, qsvm_pred))
print("Classification Report")
print(classification_report(y_test, qsvm_pred))
print("Predict the flower type for data Sepal (4.4, 4.4) and Petal (4.4, 4.4)")
qsvm_model.predict([[4.4,4.4,4.4,4.4]])

Confusion Matrix
[[12  0  2]
 [ 0 15  2]
 [ 1  3 10]]
Classification Report
                 precision    recall  f1-score   support

    Iris-setosa       0.92      0.86      0.89        14
Iris-versicolor       0.83      0.88      0.86        17
 Iris-virginica       0.71      0.71      0.71        14

       accuracy                           0.82        45
      macro avg       0.82      0.82      0.82        45
   weighted avg       0.82      0.82      0.82        45

Predict the flower type for data Sepal (4.4, 4.4) and Petal (4.4, 4.4)


array(['Iris-versicolor'], dtype=object)